"""
05_cross_event_tests.py — formal difference-in-CARs tests across events.
========================================================================
Companion to 03_event_study.py. The per-event t-tests in 03 tell you whether a
given event's CAR differs from zero; this script tests whether two events' CARs
differ FROM EACH OTHER — the formal backing for the "mirror image" claim in the
cross-event comparison (the trade-policy shock vs the military/oil-supply shock).

Test (two independent events, constant-mean model). For series X, window (0,h):
    CAR_A, CAR_B          cumulative abnormal returns, L = h+1 days each
    Var(CAR_e) = L * sigma_e^2      (sigma_e = estimation-window std of X for event e)
    diff = CAR_A - CAR_B
    SE   = sqrt(L * (sigma_A^2 + sigma_B^2))
    t    = diff / SE
Independence across the two event windows is reasonable here because the events are
far apart in calendar time (the closest pair, Liberation Day vs the twelve-day war,
is ~52 trading days apart, so the (0,h<=20) windows do not overlap).

Outputs:
  Data/processed/event_study/cross_event_diff.csv     all pairs x series x windows
  Main/LaTeX Thesis/content/tab_cross_event_diff.tex  dollar table for Section 5.3
"""

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "Data/processed"
OUT = PROC / "event_study"
TEXOUT = ROOT / "Main/LaTeX Thesis/content/tab_cross_event_diff.tex"
OUT.mkdir(parents=True, exist_ok=True)

EST_WIN = (-140, -21)   # ends before the [-20,+20] event window (matches 03)
HORIZONS = [1, 5, 10, 20]
# pairs (A, B): A - B.  First is the headline trade-policy vs military/oil contrast.
PAIRS = [("liberation_day", "hormuz"),
         ("liberation_day", "ukraine"),
         ("hormuz", "ukraine"),
         ("liberation_day", "iran_12day")]
SERIES = ["r_DTWEXBGS", "USD_EW", "SAFE", "r_DCOILBRENTEU", "r_Oil_EUR", "r_Gold_EUR"]
NICE_EV = {"liberation_day": "Liberation Day", "hormuz": "Hormuz crisis",
           "ukraine": "Ukraine", "iran_12day": "Twelve-day war"}


def stars(t):
    a = abs(t)
    return "***" if a > 2.58 else "**" if a > 1.96 else "*" if a > 1.65 else ""


def load():
    rets = pd.read_csv(PROC / "returns_daily.csv", parse_dates=["date"], index_col="date")
    ports = pd.read_csv(PROC / "portfolios_daily.csv", parse_dates=["date"], index_col="date")
    data = pd.concat([rets, ports], axis=1)
    ev = pd.read_csv(PROC / "events.csv")
    return data, dict(zip(ev["event"], ev["date"]))


def car_and_sigma(data, series, date, h):
    """Return (CAR(0,h), sigma_est, L) for one series/event under constant-mean."""
    idx = data.index
    pos = idx.searchsorted(pd.Timestamp(date))
    est = data[series].iloc[max(0, pos + EST_WIN[0]): pos + EST_WIN[1] + 1].dropna()
    evt = data[series].iloc[pos: min(len(idx), pos + h + 1)]
    if len(est) < 60 or evt.isna().all():
        return np.nan, np.nan, 0
    mu, sig = est.mean(), est.std()
    ar = evt - mu
    return ar.sum(), sig, int(ar.notna().sum())


def scale(series):
    return 1.0 if series.startswith("d_") else 100.0


if __name__ == "__main__":
    data, ev_dates = load()
    rows = []
    for ser in SERIES:
        if ser not in data.columns:
            continue
        for a, b in PAIRS:
            for h in HORIZONS:
                ca, sa, La = car_and_sigma(data, ser, ev_dates[a], h)
                cb, sb, Lb = car_and_sigma(data, ser, ev_dates[b], h)
                if La == 0 or Lb == 0 or not np.isfinite([ca, cb, sa, sb]).all():
                    continue
                L = h + 1
                diff = ca - cb
                se = np.sqrt(L * (sa ** 2 + sb ** 2))
                t = diff / se if se > 0 else np.nan
                sc = scale(ser)
                rows.append({"series": ser, "pair": f"{a}-{b}",
                             "event_A": a, "event_B": b, "window": f"(0,{h})",
                             "CAR_A_%": round(ca * sc, 3), "CAR_B_%": round(cb * sc, 3),
                             "diff_%": round(diff * sc, 3), "t": round(t, 2),
                             "sig": stars(t)})
    res = pd.DataFrame(rows)
    res.to_csv(OUT / "cross_event_diff.csv", index=False)

    # ---- LaTeX table: broad USD index, all pairs x horizons --------------------
    usd = res[res.series == "r_DTWEXBGS"]

    def cell(a, b, h):
        r = usd[(usd.event_A == a) & (usd.event_B == b) & (usd.window == f"(0,{h})")]
        if r.empty:
            return ""
        return f"${r.diff_.iloc[0]:+.2f}^{{{r.sig.iloc[0]}}}$" if False else \
               f"${r['diff_%'].iloc[0]:+.2f}" + (f"^{{{r.sig.iloc[0]}}}$" if r.sig.iloc[0] else "$")

    lines = [
        "% Generated by Code/05_cross_event_tests.py — do not edit by hand.",
        r"\begin{table}[htbp]", r"\centering", r"\begin{threeparttable}",
        r"\caption{Difference in dollar CARs across events (broad USD index, \%)}",
        r"\label{tab:es_cross_diff}", r"\small",
        r"\begin{tabular}{l rrrr}", r"\toprule",
        r" & \multicolumn{4}{c}{$\Delta\CAR(0,h)$, percentage points} \\",
        r"\cmidrule(lr){2-5}",
        r"Contrast (A $-$ B) & $h{=}1$ & $h{=}5$ & $h{=}10$ & $h{=}20$ \\", r"\midrule",
    ]
    for a, b in PAIRS:
        label = f"{NICE_EV[a]} $-$ {NICE_EV[b]}"
        lines.append(f"{label} & {cell(a,b,1)} & {cell(a,b,5)} & {cell(a,b,10)} & {cell(a,b,20)} \\\\")
    lines += [
        r"\bottomrule", r"\end{tabular}",
        r"\begin{tablenotes}[flushleft]\footnotesize",
        r"\item \textit{Notes.} Difference between two events' cumulative abnormal "
        r"returns of the broad nominal U.S.\ dollar index (\%), constant-mean model, "
        r"estimation window $[-140,-21]$. Standard error "
        r"$\sqrt{L\,(\sigma_A^2+\sigma_B^2)}$ with $L=h+1$; events treated as "
        r"independent (windows do not overlap). A positive value means the dollar rose "
        r"more (or fell less) under shock~A than shock~B. "
        r"$^{*}/^{**}/^{***}$: 10/5/1\%.",
        r"\end{tablenotes}", r"\end{threeparttable}", r"\end{table}", "",
    ]
    TEXOUT.write_text("\n".join(lines))

    print(f"Saved cross_event_diff.csv ({len(res)} rows) and {TEXOUT.name}\n")
    print("Headline — broad USD index, A - B (percentage points):")
    with pd.option_context("display.width", 130):
        print(usd[["pair", "window", "CAR_A_%", "CAR_B_%", "diff_%", "t", "sig"]]
              .to_string(index=False))
