"""
make_mm_table.py — appendix table: market-model CARs for the currency baskets.
==============================================================================
Delivers the robustness exhibit §5 promises: the safe-haven hierarchy under the
market model (vs USD_EW dollar factor) instead of the constant-mean model.
Reads Data/processed/event_study/car_summary.csv (method == market_model),
writes Main/LaTeX Thesis/content/tab_market_model.tex.

Rerun after 03_event_study.py whenever the data changes.
"""

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "Data/processed/event_study/car_summary.csv"
DST = ROOT / "Main/LaTeX Thesis/content/tab_market_model.tex"

EVENTS = [("ukraine", "Ukraine"), ("liberation_day", "Liberation Day"),
          ("iran_12day", "12-day war"), ("hormuz", "Hormuz")]
SERIES = [("SAFE", "Safe currencies"), ("RISKY", "Risky currencies"),
          ("OIL_EXP", "Oil exporters"), ("OIL_IMP", "Oil importers"),
          ("CARRY_HML", "Carry (risky$-$safe)")]
WINDOWS = ["(0,5)", "(0,20)"]


def cell(df, ev, se, win):
    r = df[(df.event == ev) & (df.series == se) & (df.window == win)]
    if r.empty:
        return "--"
    car, sig = 100 * r.CAR.iloc[0], r.sig.iloc[0]
    sig = "" if pd.isna(sig) else sig
    return f"{car:.2f}{sig}"


def main():
    d = pd.read_csv(SRC)
    d = d[d.method == "market_model"]
    lines = [
        "% Auto-generated by Code/make_mm_table.py — do not edit by hand.",
        "\\begin{table}[htbp]",
        "\\centering",
        "\\caption[Market-model CARs (robustness)]{Market-model CARs of the currency",
        "baskets (percent). Abnormal returns are residuals from a regression of each",
        "basket on the equal-weighted dollar factor estimated over the same",
        "$[-140,-21]$ window (Section~\\ref{sec:method_event}); the safe-haven",
        "hierarchy of the constant-mean results is unchanged.",
        "$^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$.}",
        "\\label{tab:market_model}",
        "\\begin{tabular}{l" + "cc" * len(EVENTS) + "}",
        "\\hline\\hline",
        " & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{lab}}}"
                           for _, lab in EVENTS) + " \\\\",
        " & " + " & ".join(["(0,5) & (0,20)"] * len(EVENTS)) + " \\\\",
        "\\hline",
    ]
    for se, lab in SERIES:
        cells = [cell(d, ev, se, w) for ev, _ in EVENTS for w in WINDOWS]
        lines.append(lab + " & " + " & ".join(cells) + " \\\\")
    lines += ["\\hline\\hline", "\\end{tabular}", "\\end{table}", ""]
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST.name} ({len(SERIES)} rows x {len(EVENTS) * 2} cells)")


if __name__ == "__main__":
    main()
